---
title: "Map of Climbing Areas I've Climbed"
author: "kat"
date: "November 26, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(leaflet)
```


>
## This map displays the first time I climbed in a particular climbing area. Click on the icon to see the name of the climbing area and a link to its Mountain Project page.

```{r, echo=FALSE, message=FALSE}
# creating data
locations <- c("Red Rock", "Yosemite", 
"The Gunks", "North Table", "Clear Creek Canyon",
 "Boulder Canyon", "Eldorado Canyon State Park", 
 "Flagstaff, Arizona", "Wanaka, New Zealand", "Shelf Road", 
 "Red River Gorge", "Rumney", "Powerlinez", "Taos, NM")


climbingSites <- c(
  "<a href='https://www.mountainproject.com/area/105731932/red-rock'>Red Rock Canyon, Nevada</a>",
  "<a href='https://www.mountainproject.com/area/105833381/yosemite-national-park'>Yosemite National Park, California</a>",
  "<a href='https://www.mountainproject.com/area/105798167/the-gunks'>The Gunks, New York</a>",
  "<a href='https://www.mountainproject.com/area/105744249/north-table-mountaingolden-cliffs'>North Table Mountain, Colorado</a>",
  "<a href='https://www.mountainproject.com/area/105744243/clear-creek-canyon'>Clear Creek Canyon, Colorado</a>", 
   "<a href='https://www.mountainproject.com/area/105744222/boulder-canyon'>Boulder Canyon, Colorado</a>", 
  "<a href='https://www.mountainproject.com/area/105744246/eldorado-canyon-sp'>Eldorado Canyon State Park, Colorado</a>", 
  "<a href='https://www.mountainproject.com/area/107448766/flagstaff-crags'>Flagstaff Crags, Arizona</a>", 
   "<a href='https://www.mountainproject.com/area/106012059/wanaka'>Wanaka, New Zealand</a>",
  "<a href='https://www.mountainproject.com/area/105744267/shelf-road'>Shelf Road, Colorado</a>",
   "<a href='https://www.mountainproject.com/area/105841134/red-river-gorge'>Red River Gorge, Kentucky</a>",
  "<a href='https://www.mountainproject.com/area/105867829/rumney'>Rumney, New Hampshire</a>",
  "<a href='https://www.mountainproject.com/area/108193801/powerlinez'>Powerlinez, New York</a>",
    "<a href='https://www.mountainproject.com/area/105868955/taos-area'>Taos, New Mexico</a>"
)


 lat <- c(36.1519, 37.8651, 41.7248, 39.79166667, 
39.82750000, 40.005856, 39.9290, 35.1983, 
44.7032, 38.622772, 37.8338, 43.8053, 41.1438, 36.4072) 


lng <- c(-115.4541, -119.5383, -74.2046, -105.2008333, 
-104.94916667, -105.334339, -105.2941, -111.6513, 169.1321,
-105.228424, -83.6084, -71.8126, -74.1605, -105.5731)

year <- c("2007", "2017", "1994", "2011", "2015", "2016", "2016", "2011", "2017",
          "2016", "2012", "2012", "2013", "2016")

color <- c("red", "green", "blue", "purple", "yellow", "orange", "orange", "purple", "green", "brown", "black", "black", "teal", "orange")

areas <- data.frame(locations=locations, climbingSites=climbingSites, lat=lat, lng=lng, year=year, col=color, stringsAsFactors = FALSE)


areas %>%
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers(color = areas$col, popup=climbingSites, clusterOptions = markerClusterOptions()) %>%
 addLegend(labels = c(1994, 2007,2011, 2012, 2013, 2015, 2016, 2017), colors = c("blue", "red", "purple","black","teal", "yellow", "orange", "green"))

```